#!/usr/bin/env bash

DIR=$(cd $(dirname $0) && pwd)

# Plan and submit the workflow generated by workflow_generator.py.
# The site, transformation, and replica catalogs are embedded in the
# workflow file, so no external catalogs or --input-dir are needed.
WORKFLOW=${1:-$DIR/workflow.yml}

if [ ! -f "$WORKFLOW" ]; then
    echo "Usage: $0 [WORKFLOW.yml]"
    echo "No workflow file at $WORKFLOW — run the generator first, e.g.:"
    echo "  ./workflow_generator.py -f input/addison.tx-*.netcdf.gz"
    exit 1
fi

pegasus-plan \
    --dir $DIR/submit \
    --sites condorpool \
    --output-site local \
    --cleanup leaf \
    --force \
    --submit \
    $WORKFLOW
