x-pegasus:
  apiLang: python
  createdBy: panorama
  createdOn: 12-01-21T21:30:35Z
pegasus: '5.0'
name: casa-wind
transformationCatalog:
  transformations:
  - name: gunzip
    sites:
    - name: condorpool
      pfn: /bin/gunzip
      type: installed
      container: casa_wind_cont
  - name: um_vel
    sites:
    - name: condorpool
      pfn: /opt/UM_VEL/UM_VEL
      type: installed
      container: casa_wind_cont
  - name: post_vel
    sites:
    - name: condorpool
      pfn: /opt/netcdf2png/merged_netcdf2png
      type: installed
      container: casa_wind_cont
  - name: mvt
    sites:
    - name: condorpool
      pfn: /opt/mvt/mvt
      type: installed
      container: casa_wind_cont
  - name: point_alert
    sites:
    - name: condorpool
      pfn: /opt/pointAlert/pointAlert
      type: installed
      container: casa_wind_cont
  containers:
  - name: casa_wind_cont
    type: singularity
    image: /usr/bin/casa-wind_latest.sif
    mounts:
    - /home/panorama/public_html:/home/panorama/public_html:ro
    image.site: condorpool
jobs:
- type: job
  name: gunzip
  id: gunzip_0
  arguments:
  - --force
  - denton.tx-20170329-072801.netcdf.gz
  uses:
  - lfn: denton.tx-20170329-072801.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_1
  arguments:
  - --force
  - cleburne.tx-20170329-072802.netcdf.gz
  uses:
  - lfn: cleburne.tx-20170329-072802.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_2
  arguments:
  - --force
  - midlothian.tx-20170329-072807.netcdf.gz
  uses:
  - lfn: midlothian.tx-20170329-072807.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_3
  arguments:
  - --force
  - mesquite.tx-20170329-072807.netcdf.gz
  uses:
  - lfn: mesquite.tx-20170329-072807.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_4
  arguments:
  - --force
  - ftworth.tx-20170329-072811.netcdf.gz
  uses:
  - lfn: ftworth.tx-20170329-072811.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_5
  arguments:
  - --force
  - arlington.tx-20170329-072815.netcdf.gz
  uses:
  - lfn: arlington.tx-20170329-072815.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_6
  arguments:
  - --force
  - cleburne.tx-20170329-072825.netcdf.gz
  uses:
  - lfn: cleburne.tx-20170329-072825.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_7
  arguments:
  - --force
  - midlothian.tx-20170329-072827.netcdf.gz
  uses:
  - lfn: midlothian.tx-20170329-072827.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_8
  arguments:
  - --force
  - denton.tx-20170329-072827.netcdf.gz
  uses:
  - lfn: denton.tx-20170329-072827.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_9
  arguments:
  - --force
  - mesquite.tx-20170329-072827.netcdf.gz
  uses:
  - lfn: mesquite.tx-20170329-072827.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_10
  arguments:
  - --force
  - ftworth.tx-20170329-072831.netcdf.gz
  uses:
  - lfn: ftworth.tx-20170329-072831.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_11
  arguments:
  - --force
  - arlington.tx-20170329-072835.netcdf.gz
  uses:
  - lfn: arlington.tx-20170329-072835.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_12
  arguments:
  - --force
  - addison.tx-20170329-072843.netcdf.gz
  uses:
  - lfn: addison.tx-20170329-072843.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_13
  arguments:
  - --force
  - midlothian.tx-20170329-072847.netcdf.gz
  uses:
  - lfn: midlothian.tx-20170329-072847.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_14
  arguments:
  - --force
  - mesquite.tx-20170329-072847.netcdf.gz
  uses:
  - lfn: mesquite.tx-20170329-072847.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_15
  arguments:
  - --force
  - ftworth.tx-20170329-072851.netcdf.gz
  uses:
  - lfn: ftworth.tx-20170329-072851.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_16
  arguments:
  - --force
  - arlington.tx-20170329-072855.netcdf.gz
  uses:
  - lfn: arlington.tx-20170329-072855.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_17
  arguments:
  - --force
  - denton.tx-20170329-072900.netcdf.gz
  uses:
  - lfn: denton.tx-20170329-072900.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_18
  arguments:
  - --force
  - cleburne.tx-20170329-072902.netcdf.gz
  uses:
  - lfn: cleburne.tx-20170329-072902.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_19
  arguments:
  - --force
  - mesquite.tx-20170329-072907.netcdf.gz
  uses:
  - lfn: mesquite.tx-20170329-072907.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_20
  arguments:
  - --force
  - midlothian.tx-20170329-072907.netcdf.gz
  uses:
  - lfn: midlothian.tx-20170329-072907.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_21
  arguments:
  - --force
  - ftworth.tx-20170329-072911.netcdf.gz
  uses:
  - lfn: ftworth.tx-20170329-072911.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_22
  arguments:
  - --force
  - arlington.tx-20170329-072915.netcdf.gz
  uses:
  - lfn: arlington.tx-20170329-072915.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_23
  arguments:
  - --force
  - cleburne.tx-20170329-072925.netcdf.gz
  uses:
  - lfn: cleburne.tx-20170329-072925.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_24
  arguments:
  - --force
  - midlothian.tx-20170329-072927.netcdf.gz
  uses:
  - lfn: midlothian.tx-20170329-072927.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_25
  arguments:
  - --force
  - mesquite.tx-20170329-072927.netcdf.gz
  uses:
  - lfn: mesquite.tx-20170329-072927.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: gunzip
  id: gunzip_26
  arguments:
  - --force
  - denton.tx-20170329-072927.netcdf.gz
  uses:
  - lfn: denton.tx-20170329-072927.netcdf.gz
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: um_vel
  id: um_vel
  arguments:
  - denton.tx-20170329-072801.netcdf
  - cleburne.tx-20170329-072802.netcdf
  - midlothian.tx-20170329-072807.netcdf
  - mesquite.tx-20170329-072807.netcdf
  - ftworth.tx-20170329-072811.netcdf
  - arlington.tx-20170329-072815.netcdf
  - cleburne.tx-20170329-072825.netcdf
  - midlothian.tx-20170329-072827.netcdf
  - denton.tx-20170329-072827.netcdf
  - mesquite.tx-20170329-072827.netcdf
  - ftworth.tx-20170329-072831.netcdf
  - arlington.tx-20170329-072835.netcdf
  - addison.tx-20170329-072843.netcdf
  - midlothian.tx-20170329-072847.netcdf
  - mesquite.tx-20170329-072847.netcdf
  - ftworth.tx-20170329-072851.netcdf
  - arlington.tx-20170329-072855.netcdf
  - denton.tx-20170329-072900.netcdf
  - cleburne.tx-20170329-072902.netcdf
  - mesquite.tx-20170329-072907.netcdf
  - midlothian.tx-20170329-072907.netcdf
  - ftworth.tx-20170329-072911.netcdf
  - arlington.tx-20170329-072915.netcdf
  - cleburne.tx-20170329-072925.netcdf
  - midlothian.tx-20170329-072927.netcdf
  - mesquite.tx-20170329-072927.netcdf
  - denton.tx-20170329-072927.netcdf
  uses:
  - lfn: MaxVelocity_20170329-072927.netcdf
    type: output
    stageOut: false
    registerReplica: false
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: post_vel
  id: ID0000001
  arguments:
  - -c
  - max_wind.png
  - -q 235 -z 11.176,38
  - -o
  - MaxVelocity_20170329-072927.png
  - MaxVelocity_20170329-072927.netcdf
  uses:
  - lfn: max_wind.png
    type: input
  - lfn: MaxVelocity_20170329-072927.netcdf
    type: input
  - lfn: MaxVelocity_20170329-072927.png
    type: output
    stageOut: true
    registerReplica: false
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
- type: job
  name: mvt
  id: ID0000002
  arguments:
  - MaxVelocity_20170329-072927.netcdf
  uses:
  - lfn: MaxVelocity_20170329-072927.netcdf
    type: input
  - lfn: mvt_MaxVelocity_20170329-072927.geojson
    type: output
    stageOut: false
    registerReplica: false
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
- type: job
  name: point_alert
  id: ID0000003
  arguments:
  - -c
  - pointAlert_config.txt
  - -p
  - -o
  - alert_20170329-072927.geojson
  - -g
  - hospital_locations.geojson
  - mvt_MaxVelocity_20170329-072927.geojson
  uses:
  - lfn: alert_20170329-072927.geojson
    type: output
    stageOut: true
    registerReplica: false
  - lfn: pointAlert_config.txt
    type: input
  - lfn: hospital_locations.geojson
    type: input
  - lfn: mvt_MaxVelocity_20170329-072927.geojson
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
jobDependencies:
- id: gunzip_0
  children:
  - um_vel
- id: gunzip_1
  children:
  - um_vel
- id: gunzip_2
  children:
  - um_vel
- id: gunzip_3
  children:
  - um_vel
- id: gunzip_4
  children:
  - um_vel
- id: gunzip_5
  children:
  - um_vel
- id: gunzip_6
  children:
  - um_vel
- id: gunzip_7
  children:
  - um_vel
- id: gunzip_8
  children:
  - um_vel
- id: gunzip_9
  children:
  - um_vel
- id: gunzip_10
  children:
  - um_vel
- id: gunzip_11
  children:
  - um_vel
- id: gunzip_12
  children:
  - um_vel
- id: gunzip_13
  children:
  - um_vel
- id: gunzip_14
  children:
  - um_vel
- id: gunzip_15
  children:
  - um_vel
- id: gunzip_16
  children:
  - um_vel
- id: gunzip_17
  children:
  - um_vel
- id: gunzip_18
  children:
  - um_vel
- id: gunzip_19
  children:
  - um_vel
- id: gunzip_20
  children:
  - um_vel
- id: gunzip_21
  children:
  - um_vel
- id: gunzip_22
  children:
  - um_vel
- id: gunzip_23
  children:
  - um_vel
- id: gunzip_24
  children:
  - um_vel
- id: gunzip_25
  children:
  - um_vel
- id: gunzip_26
  children:
  - um_vel
- id: um_vel
  children:
  - ID0000001
  - ID0000002
- id: ID0000002
  children:
  - ID0000003
