x-pegasus:
  apiLang: python
  createdBy: panorama
  createdOn: 11-30-21T02:51:01Z
pegasus: '5.0'
name: casa_wind_wf-20211130T025101Z
transformationCatalog:
  transformations:
  - name: unzip
    sites:
    - name: condorpool
      pfn: /bin/gunzip
      type: installed
  - name: um_vel
    sites:
    - name: condorpool
      pfn: opt/UM_VEL/UM_VEL
      type: installed
      container: casa_wind_cont
  - name: post_vel
    sites:
    - name: condorpool
      pfn: /opt/netcdf2png/merged_netcdf2png
      type: installed
      container: casa_wind_cont
  - name: mvt
    sites:
    - name: condorpool
      pfn: /opt/mvt/mvt
      type: installed
      container: casa_wind_cont
  - name: point_alert
    sites:
    - name: condorpool
      pfn: /opt/pointAlert/pointAlert
      type: installed
      container: casa_wind_cont
  containers:
  - name: casa_wind_cont
    type: docker
    image: docker:///pegasus/casa-wind
jobs:
- type: job
  name: um_vel
  id: ID0000001
  arguments:
  - ''
  uses:
  - lfn: MaxVelocity_20170329-072328.netcdf
    type: output
    stageOut: true
    registerReplica: true
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 1
    pegasus:
      label: top
- type: job
  name: post_vel
  id: ID0000002
  arguments:
  - -c
  - max_wind.png
  - -q 235 -z 11.176,38
  - -o
  - MaxVelocity_20170329-072328.png
  - MaxVelocity_20170329-072328.netcdf
  uses:
  - lfn: MaxVelocity_20170329-072328.png
    type: output
    stageOut: true
    registerReplica: true
  - lfn: max_wind.png
    type: input
  - lfn: MaxVelocity_20170329-072328.netcdf
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
- type: job
  name: mvt
  id: ID0000003
  arguments:
  - MaxVelocity_20170329-072328.netcdf
  uses:
  - lfn: MaxVelocity_20170329-072328.netcdf
    type: input
  - lfn: mvt_MaxVelocity_20170329-072328.geojson
    type: output
    stageOut: true
    registerReplica: true
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
- type: job
  name: point_alert
  id: ID0000004
  arguments:
  - -c
  - pointAlert_config.txt
  - -p
  - -o
  - alert_20170329-072328.geojson
  - -g
  - hospital_locations.geojson
  - mvt_MaxVelocity_20170329-072328.geojson
  uses:
  - lfn: hospital_locations.geojson
    type: input
  - lfn: mvt_MaxVelocity_20170329-072328.geojson
    type: input
  - lfn: alert_20170329-072328.geojson
    type: output
    stageOut: true
    registerReplica: true
  - lfn: pointAlert_config.txt
    type: input
  profiles:
    condor:
      requirements: MACHINE_SPECIAL_ID == 0
    pegasus:
      label: bottom
jobDependencies:
- id: ID0000001
  children:
  - ID0000003
  - ID0000002
- id: ID0000003
  children:
  - ID0000004
